function [domain, seed] = create_domain_from_struct_with_seed(domainStruct, seed)
%CREATE_DOMAIN_FROM_STRUCT 

[domain, seed] = create_domain_with_seed(...
    domainStruct.gridSize, ...
    domainStruct.noiseLevel, ...
    domainStruct.predators, ...
    domainStruct.prey, ...
    seed);

domain.lockingState = domainStruct.lockingState;